### ISSUE TITLE
rime-ice is not shown in schema list

### ISSUE THREAD

**Issue by 12-G** [linyinfeng/nur-packages#864]
Hi, I am curious about why I cannot use rime-ice.My code for fcitx5-rime and default.custom.yaml:
```nix
{
  pkgs,
  lib,
  config,
  ...
}: {
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    fcitx5.waylandFrontend = true;
    fcitx5.addons = with pkgs; [
      (fcitx5-rime.override {
        rimeDataPkgs =
          [
            pkgs.rime-data
          ]
          ++ (with pkgs.nur.repos.linyinfeng.rimePackages;
            withRimeDeps [
              rime-ice
            ]);
      })
      fcitx5-chinese-addons
      fcitx5-gtk
    ];
  };

# Extra variables not covered by Nixos fcitx module
# Author: Lan tian
  environment.variables = lib.mkIf (!config.i18n.inputMethod.fcitx5.waylandFrontend) {
    INPUT_METHOD = "fcitx";
    SDL_IM_MODULE = "fcitx";
    GLFW_IM_MODULE = "ibus";
    QT_IM_MODULES = "wayland;fcitx;ibus";
  };
}
```
```yaml
patch:
  # 仅使用「雾凇拼音」的默认配置，配置此行即可
  __include: rime_ice_suggestion:/
  # 以下根据自己所需自行定义，仅做参考。
  # 针对对应处方的定制条目，请使用 <recipe>.custom.yaml 中配置，例如 rime_ice.custom.yaml
  __patch:
    menu/page_size: 5
    key_binder/bindings/+:
      # 开启逗号句号翻页
      - { when: paging, accept: comma, send: Page_Up }
      - { when: has_menu, accept: period, send: Page_Down }
```
![image](https://github.com/user-attachments/assets/91b7437d-d48b-4163-b69c-96a57b2060d1)
